name: 'Dev'

on:
  push:
    branches:
    - main

jobs:
  Dev:
    name: 'Deploy-to-Dev'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init 
      id: init
      run: terraform -chdir=Dev init
 
    - name: Terraform Plan 
      id: plan
      run: terraform -chdir=Dev plan 
      continue-on-error: true

#    - name: Terraform Apply 
#      run: terraform -chdir=Dev apply -auto-approve

#    - name: Terraform Destroy
#      run: terraform -chdir=Dev destroy -auto-approve