name: 'Stg'

on:
  push:
    branches:
    - main

jobs:
  Dev:
    name: 'Deploy-to-Stg'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1 

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init 
      id: init
      run: terraform -chdir=Stg init
 
    - name: Terraform Plan 
      id: plan
      run: terraform -chdir=Stg plan 
      continue-on-error: true

    - name: Terraform Apply 
      run: terraform -chdir=Stg apply -auto-approve

    - name: Terraform Destroy
      run: terraform -chdir=Stg destroy -auto-approve